# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 599394a97606877cecbaf815df65878f8d057c8c922f8077abdd615d324497e3c018ce3916d751a27f074ba92c44c52f7b9f661735642e151591e58cb7109a89

test:
  secret_key_base: bd41acba3ac685d5641ba4f8cdd9b7b4e6715a1d5987d8ecdf9997d2dfe62852a52b3b4e026198db234227a63a420c807178d85fa5ebdeb4a424750d269443fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
